### ISSUE TITLE
logo and brand name

### ISSUE THREAD

**Issue by smitdhimar** [DhruvItaliya/hackathon#15]
above mentioned two things should be decided , so more complete ui components can be build.
we connect is the one name which randomly came into mine thoughts.

**Comment by Mustu19** [comment]
Its good. I also thought one name of our company that is "FeedingForward" . What do you think?

**Comment by smitdhimar** [comment]
"Feeding Forward" might not be most suitable

**Comment by smitdhimar** [comment]
![names](https://github.com/DhruvItaliya/hackathon/assets/104231844/34d65116-b182-4e2b-8e36-979e20a92c1b)
